source 'https://rubygems.org'

gem 'concurrent-ruby', '~>1.0'
gem 'forecast_io', '~>2.0'
gem 'json', '>=2.3'
gem 'oga', '~>2.0'
gem 'redd', '=0.8.1'
gem 'tabulo', '~>2.2'
gem 'twitch-api', '>=0.3.0'
gem 'unicode-emoji', '>=1.1.0'
